#include <efi.h>
#include <efilib.h>

#ifdef __x86_64__
typedef unsigned long long size_t;
#else
typedef unsigned long size_t;
#endif

// Generated by objcopy to point to embedded kernel binary
extern uint8_t _binary_kernel_start[];
extern uint8_t _binary_kernel_size[];

EFI_STATUS efi_main(EFI_HANDLE imageHandle, EFI_SYSTEM_TABLE* systemTable)
{
    InitializeLib(imageHandle, systemTable);
    return EFI_SUCCESS;
}

